Traceback (most recent call last):
  File "/root/news_site_scraper/dusit-international.py", line 289, in <module>
    if date_text == date_format(datetime.now().today()):
NameError: name 'date_text' is not defined
Traceback (most recent call last):
  File "/root/news_site_scraper/dusit-international.py", line 289, in <module>
    if date_text == date_format(datetime.now().today()):
NameError: name 'date_text' is not defined
Traceback (most recent call last):
  File "/root/news_site_scraper/dusit-international.py", line 289, in <module>
    if date_text == date_format(datetime.now().today()):
NameError: name 'date_text' is not defined
Date: Date not found
Title: Title not found
URL: URL not found
Traceback (most recent call last):
  File "/root/news_site_scraper/dusit-international.py", line 111, in <module>
    driver.get(href)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 393, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=131.0.6778.204)
Stacktrace:
#0 0x561033f938fa <unknown>
#1 0x561033aa4b7d <unknown>
#2 0x561033a8c64f <unknown>
#3 0x561033a8ac55 <unknown>
#4 0x561033a8b37a <unknown>
#5 0x561033aa7649 <unknown>
#6 0x561033b371b5 <unknown>
#7 0x561033b17af2 <unknown>
#8 0x561033b36560 <unknown>
#9 0x561033b17893 <unknown>
#10 0x561033ae630d <unknown>
#11 0x561033ae732e <unknown>
#12 0x561033f6000b <unknown>
#13 0x561033f63f97 <unknown>
#14 0x561033f4c71c <unknown>
#15 0x561033f64b17 <unknown>
#16 0x561033f316cf <unknown>
#17 0x561033f826b8 <unknown>
#18 0x561033f82880 <unknown>
#19 0x561033f92776 <unknown>
#20 0x7fa884edfac3 <unknown>

Date: Date not found
Title: Title not found
URL: URL not found
Traceback (most recent call last):
  File "/root/news_site_scraper/dusit-international.py", line 111, in <module>
    driver.get(href)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 393, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=131.0.6778.204)
Stacktrace:
#0 0x55ab3a0258fa <unknown>
#1 0x55ab39b36b7d <unknown>
#2 0x55ab39b1e64f <unknown>
#3 0x55ab39b1cc55 <unknown>
#4 0x55ab39b1d37a <unknown>
#5 0x55ab39b39649 <unknown>
#6 0x55ab39bc91b5 <unknown>
#7 0x55ab39ba9af2 <unknown>
#8 0x55ab39bc8560 <unknown>
#9 0x55ab39ba9893 <unknown>
#10 0x55ab39b7830d <unknown>
#11 0x55ab39b7932e <unknown>
#12 0x55ab39ff200b <unknown>
#13 0x55ab39ff5f97 <unknown>
#14 0x55ab39fde71c <unknown>
#15 0x55ab39ff6b17 <unknown>
#16 0x55ab39fc36cf <unknown>
#17 0x55ab3a0146b8 <unknown>
#18 0x55ab3a014880 <unknown>
#19 0x55ab3a024776 <unknown>
#20 0x7fd1f3a02ac3 <unknown>

Date: Date not found
Title: Title not found
URL: URL not found
Traceback (most recent call last):
  File "/root/news_site_scraper/dusit-international.py", line 111, in <module>
    driver.get(href)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 393, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=131.0.6778.204)
Stacktrace:
#0 0x55d9daa118fa <unknown>
#1 0x55d9da522b7d <unknown>
#2 0x55d9da50a64f <unknown>
#3 0x55d9da508c55 <unknown>
#4 0x55d9da50937a <unknown>
#5 0x55d9da525649 <unknown>
#6 0x55d9da5b51b5 <unknown>
#7 0x55d9da595af2 <unknown>
#8 0x55d9da5b4560 <unknown>
#9 0x55d9da595893 <unknown>
#10 0x55d9da56430d <unknown>
#11 0x55d9da56532e <unknown>
#12 0x55d9da9de00b <unknown>
#13 0x55d9da9e1f97 <unknown>
#14 0x55d9da9ca71c <unknown>
#15 0x55d9da9e2b17 <unknown>
#16 0x55d9da9af6cf <unknown>
#17 0x55d9daa006b8 <unknown>
#18 0x55d9daa00880 <unknown>
#19 0x55d9daa10776 <unknown>
#20 0x7fcb4bb9aac3 <unknown>

Date: Date not found
Title: Title not found
URL: URL not found
Traceback (most recent call last):
  File "/root/news_site_scraper/dusit-international.py", line 111, in <module>
    driver.get(href)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 393, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=131.0.6778.204)
Stacktrace:
#0 0x55d20aebc8fa <unknown>
#1 0x55d20a9cdb7d <unknown>
#2 0x55d20a9b564f <unknown>
#3 0x55d20a9b3c55 <unknown>
#4 0x55d20a9b437a <unknown>
#5 0x55d20a9d0649 <unknown>
#6 0x55d20aa601b5 <unknown>
#7 0x55d20aa40af2 <unknown>
#8 0x55d20aa5f560 <unknown>
#9 0x55d20aa40893 <unknown>
#10 0x55d20aa0f30d <unknown>
#11 0x55d20aa1032e <unknown>
#12 0x55d20ae8900b <unknown>
#13 0x55d20ae8cf97 <unknown>
#14 0x55d20ae7571c <unknown>
#15 0x55d20ae8db17 <unknown>
#16 0x55d20ae5a6cf <unknown>
#17 0x55d20aeab6b8 <unknown>
#18 0x55d20aeab880 <unknown>
#19 0x55d20aebb776 <unknown>
#20 0x7f034bd24ac3 <unknown>

