Traceback (most recent call last):
  File "/root/news_site_scraper/karismahotels.py", line 159, in <module>
    driver = webdriver.Chrome()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5589429c08fa <unknown>
#1 0x5589424d1d20 <unknown>
#2 0x558942509438 <unknown>
#3 0x558942504f96 <unknown>
#4 0x558942550d86 <unknown>
#5 0x5589425503d6 <unknown>
#6 0x558942544893 <unknown>
#7 0x55894251330d <unknown>
#8 0x55894251432e <unknown>
#9 0x55894298d00b <unknown>
#10 0x558942990f97 <unknown>
#11 0x55894297971c <unknown>
#12 0x558942991b17 <unknown>
#13 0x55894295e6cf <unknown>
#14 0x5589429af6b8 <unknown>
#15 0x5589429af880 <unknown>
#16 0x5589429bf776 <unknown>
#17 0x7f30efb3aac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/karismahotels.py", line 159, in <module>
    driver = webdriver.Chrome()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5561ec9ab8fa <unknown>
#1 0x5561ec4bcd20 <unknown>
#2 0x5561ec4f4438 <unknown>
#3 0x5561ec4eff96 <unknown>
#4 0x5561ec53bd86 <unknown>
#5 0x5561ec53b3d6 <unknown>
#6 0x5561ec52f893 <unknown>
#7 0x5561ec4fe30d <unknown>
#8 0x5561ec4ff32e <unknown>
#9 0x5561ec97800b <unknown>
#10 0x5561ec97bf97 <unknown>
#11 0x5561ec96471c <unknown>
#12 0x5561ec97cb17 <unknown>
#13 0x5561ec9496cf <unknown>
#14 0x5561ec99a6b8 <unknown>
#15 0x5561ec99a880 <unknown>
#16 0x5561ec9aa776 <unknown>
#17 0x7fc8db251ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/karismahotels.py", line 159, in <module>
    driver = webdriver.Chrome()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55f2b84298fa <unknown>
#1 0x55f2b7f3ad20 <unknown>
#2 0x55f2b7f72438 <unknown>
#3 0x55f2b7f6df96 <unknown>
#4 0x55f2b7fb9d86 <unknown>
#5 0x55f2b7fb93d6 <unknown>
#6 0x55f2b7fad893 <unknown>
#7 0x55f2b7f7c30d <unknown>
#8 0x55f2b7f7d32e <unknown>
#9 0x55f2b83f600b <unknown>
#10 0x55f2b83f9f97 <unknown>
#11 0x55f2b83e271c <unknown>
#12 0x55f2b83fab17 <unknown>
#13 0x55f2b83c76cf <unknown>
#14 0x55f2b84186b8 <unknown>
#15 0x55f2b8418880 <unknown>
#16 0x55f2b8428776 <unknown>
#17 0x7f16fcedbac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/karismahotels.py", line 159, in <module>
    driver = webdriver.Chrome()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55df9b0988fa <unknown>
#1 0x55df9aba9d20 <unknown>
#2 0x55df9abe1438 <unknown>
#3 0x55df9abdcf96 <unknown>
#4 0x55df9ac28d86 <unknown>
#5 0x55df9ac283d6 <unknown>
#6 0x55df9ac1c893 <unknown>
#7 0x55df9abeb30d <unknown>
#8 0x55df9abec32e <unknown>
#9 0x55df9b06500b <unknown>
#10 0x55df9b068f97 <unknown>
#11 0x55df9b05171c <unknown>
#12 0x55df9b069b17 <unknown>
#13 0x55df9b0366cf <unknown>
#14 0x55df9b0876b8 <unknown>
#15 0x55df9b087880 <unknown>
#16 0x55df9b097776 <unknown>
#17 0x7fd7fc5c5ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/karismahotels.py", line 159, in <module>
    driver = webdriver.Chrome()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x561e932aa8fa <unknown>
#1 0x561e92dbbd20 <unknown>
#2 0x561e92df3438 <unknown>
#3 0x561e92deef96 <unknown>
#4 0x561e92e3ad86 <unknown>
#5 0x561e92e3a3d6 <unknown>
#6 0x561e92e2e893 <unknown>
#7 0x561e92dfd30d <unknown>
#8 0x561e92dfe32e <unknown>
#9 0x561e9327700b <unknown>
#10 0x561e9327af97 <unknown>
#11 0x561e9326371c <unknown>
#12 0x561e9327bb17 <unknown>
#13 0x561e932486cf <unknown>
#14 0x561e932996b8 <unknown>
#15 0x561e93299880 <unknown>
#16 0x561e932a9776 <unknown>
#17 0x7ff2e0072ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/karismahotels.py", line 159, in <module>
    driver = webdriver.Chrome()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55590a3818fa <unknown>
#1 0x555909e92d20 <unknown>
#2 0x555909eca438 <unknown>
#3 0x555909ec5f96 <unknown>
#4 0x555909f11d86 <unknown>
#5 0x555909f113d6 <unknown>
#6 0x555909f05893 <unknown>
#7 0x555909ed430d <unknown>
#8 0x555909ed532e <unknown>
#9 0x55590a34e00b <unknown>
#10 0x55590a351f97 <unknown>
#11 0x55590a33a71c <unknown>
#12 0x55590a352b17 <unknown>
#13 0x55590a31f6cf <unknown>
#14 0x55590a3706b8 <unknown>
#15 0x55590a370880 <unknown>
#16 0x55590a380776 <unknown>
#17 0x7f508e075ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/karismahotels.py", line 159, in <module>
    driver = webdriver.Chrome()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5607597468fa <unknown>
#1 0x560759257d20 <unknown>
#2 0x56075928f438 <unknown>
#3 0x56075928af96 <unknown>
#4 0x5607592d6d86 <unknown>
#5 0x5607592d63d6 <unknown>
#6 0x5607592ca893 <unknown>
#7 0x56075929930d <unknown>
#8 0x56075929a32e <unknown>
#9 0x56075971300b <unknown>
#10 0x560759716f97 <unknown>
#11 0x5607596ff71c <unknown>
#12 0x560759717b17 <unknown>
#13 0x5607596e46cf <unknown>
#14 0x5607597356b8 <unknown>
#15 0x560759735880 <unknown>
#16 0x560759745776 <unknown>
#17 0x7f5202a3dac3 <unknown>

