Error: Message: 
Stacktrace:
#0 0x55d4a78a58fa <unknown>
#1 0x55d4a73b6d20 <unknown>
#2 0x55d4a7405a66 <unknown>
#3 0x55d4a7405d01 <unknown>
#4 0x55d4a744b184 <unknown>
#5 0x55d4a7429b1d <unknown>
#6 0x55d4a7448560 <unknown>
#7 0x55d4a7429893 <unknown>
#8 0x55d4a73f830d <unknown>
#9 0x55d4a73f932e <unknown>
#10 0x55d4a787200b <unknown>
#11 0x55d4a7875f97 <unknown>
#12 0x55d4a785e71c <unknown>
#13 0x55d4a7876b17 <unknown>
#14 0x55d4a78436cf <unknown>
#15 0x55d4a78946b8 <unknown>
#16 0x55d4a7894880 <unknown>
#17 0x55d4a78a4776 <unknown>
#18 0x7fd281dd7ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/leonardo.py", line 173, in <module>
    if date_format(date) ==  datetime.now().today():
NameError: name 'date' is not defined. Did you mean: 'data'?
Error: Message: 
Stacktrace:
#0 0x5622fa6128fa <unknown>
#1 0x5622fa123d20 <unknown>
#2 0x5622fa172a66 <unknown>
#3 0x5622fa172d01 <unknown>
#4 0x5622fa1b8184 <unknown>
#5 0x5622fa196b1d <unknown>
#6 0x5622fa1b5560 <unknown>
#7 0x5622fa196893 <unknown>
#8 0x5622fa16530d <unknown>
#9 0x5622fa16632e <unknown>
#10 0x5622fa5df00b <unknown>
#11 0x5622fa5e2f97 <unknown>
#12 0x5622fa5cb71c <unknown>
#13 0x5622fa5e3b17 <unknown>
#14 0x5622fa5b06cf <unknown>
#15 0x5622fa6016b8 <unknown>
#16 0x5622fa601880 <unknown>
#17 0x5622fa611776 <unknown>
#18 0x7fd0c9e45ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/leonardo.py", line 173, in <module>
    if date_format(date) ==  datetime.now().today():
NameError: name 'date' is not defined. Did you mean: 'data'?
Error: Message: 
Stacktrace:
#0 0x55bce12f68fa <unknown>
#1 0x55bce0e07d20 <unknown>
#2 0x55bce0e56a66 <unknown>
#3 0x55bce0e56d01 <unknown>
#4 0x55bce0e9c184 <unknown>
#5 0x55bce0e7ab1d <unknown>
#6 0x55bce0e99560 <unknown>
#7 0x55bce0e7a893 <unknown>
#8 0x55bce0e4930d <unknown>
#9 0x55bce0e4a32e <unknown>
#10 0x55bce12c300b <unknown>
#11 0x55bce12c6f97 <unknown>
#12 0x55bce12af71c <unknown>
#13 0x55bce12c7b17 <unknown>
#14 0x55bce12946cf <unknown>
#15 0x55bce12e56b8 <unknown>
#16 0x55bce12e5880 <unknown>
#17 0x55bce12f5776 <unknown>
#18 0x7fb6ce7a0ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/leonardo.py", line 173, in <module>
    if date_format(date) ==  datetime.now().today():
NameError: name 'date' is not defined. Did you mean: 'data'?
Error: Message: 
Stacktrace:
#0 0x55a02a91d8fa <unknown>
#1 0x55a02a42ed20 <unknown>
#2 0x55a02a47da66 <unknown>
#3 0x55a02a47dd01 <unknown>
#4 0x55a02a4c3184 <unknown>
#5 0x55a02a4a1b1d <unknown>
#6 0x55a02a4c0560 <unknown>
#7 0x55a02a4a1893 <unknown>
#8 0x55a02a47030d <unknown>
#9 0x55a02a47132e <unknown>
#10 0x55a02a8ea00b <unknown>
#11 0x55a02a8edf97 <unknown>
#12 0x55a02a8d671c <unknown>
#13 0x55a02a8eeb17 <unknown>
#14 0x55a02a8bb6cf <unknown>
#15 0x55a02a90c6b8 <unknown>
#16 0x55a02a90c880 <unknown>
#17 0x55a02a91c776 <unknown>
#18 0x7f9617b91ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/leonardo.py", line 173, in <module>
    if date_format(date) ==  datetime.now().today():
NameError: name 'date' is not defined. Did you mean: 'data'?
Error: Message: 
Stacktrace:
#0 0x55de6f13c8fa <unknown>
#1 0x55de6ec4dd20 <unknown>
#2 0x55de6ec9ca66 <unknown>
#3 0x55de6ec9cd01 <unknown>
#4 0x55de6ece2184 <unknown>
#5 0x55de6ecc0b1d <unknown>
#6 0x55de6ecdf560 <unknown>
#7 0x55de6ecc0893 <unknown>
#8 0x55de6ec8f30d <unknown>
#9 0x55de6ec9032e <unknown>
#10 0x55de6f10900b <unknown>
#11 0x55de6f10cf97 <unknown>
#12 0x55de6f0f571c <unknown>
#13 0x55de6f10db17 <unknown>
#14 0x55de6f0da6cf <unknown>
#15 0x55de6f12b6b8 <unknown>
#16 0x55de6f12b880 <unknown>
#17 0x55de6f13b776 <unknown>
#18 0x7fb720f64ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/leonardo.py", line 173, in <module>
    if date_format(date) ==  datetime.now().today():
NameError: name 'date' is not defined. Did you mean: 'data'?
Error: Message: 
Stacktrace:
#0 0x5588268e48fa <unknown>
#1 0x5588263f5d20 <unknown>
#2 0x558826444a66 <unknown>
#3 0x558826444d01 <unknown>
#4 0x55882648a184 <unknown>
#5 0x558826468b1d <unknown>
#6 0x558826487560 <unknown>
#7 0x558826468893 <unknown>
#8 0x55882643730d <unknown>
#9 0x55882643832e <unknown>
#10 0x5588268b100b <unknown>
#11 0x5588268b4f97 <unknown>
#12 0x55882689d71c <unknown>
#13 0x5588268b5b17 <unknown>
#14 0x5588268826cf <unknown>
#15 0x5588268d36b8 <unknown>
#16 0x5588268d3880 <unknown>
#17 0x5588268e3776 <unknown>
#18 0x7f9587592ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/leonardo.py", line 173, in <module>
    if date_format(date) ==  datetime.now().today():
NameError: name 'date' is not defined. Did you mean: 'data'?
Error: Message: 
Stacktrace:
#0 0x562a6e2a38fa <unknown>
#1 0x562a6ddb4d20 <unknown>
#2 0x562a6de03a66 <unknown>
#3 0x562a6de03d01 <unknown>
#4 0x562a6de49184 <unknown>
#5 0x562a6de27b1d <unknown>
#6 0x562a6de46560 <unknown>
#7 0x562a6de27893 <unknown>
#8 0x562a6ddf630d <unknown>
#9 0x562a6ddf732e <unknown>
#10 0x562a6e27000b <unknown>
#11 0x562a6e273f97 <unknown>
#12 0x562a6e25c71c <unknown>
#13 0x562a6e274b17 <unknown>
#14 0x562a6e2416cf <unknown>
#15 0x562a6e2926b8 <unknown>
#16 0x562a6e292880 <unknown>
#17 0x562a6e2a2776 <unknown>
#18 0x7fa894f1fac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/leonardo.py", line 173, in <module>
    if date_format(date) ==  datetime.now().today():
NameError: name 'date' is not defined. Did you mean: 'data'?
