Traceback (most recent call last):
  File "/root/news_site_scraper/lhw.py", line 128, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55ac073138fa <unknown>
#1 0x55ac06e24d20 <unknown>
#2 0x55ac06e5c438 <unknown>
#3 0x55ac06e57f96 <unknown>
#4 0x55ac06ea3d86 <unknown>
#5 0x55ac06ea33d6 <unknown>
#6 0x55ac06e97893 <unknown>
#7 0x55ac06e6630d <unknown>
#8 0x55ac06e6732e <unknown>
#9 0x55ac072e000b <unknown>
#10 0x55ac072e3f97 <unknown>
#11 0x55ac072cc71c <unknown>
#12 0x55ac072e4b17 <unknown>
#13 0x55ac072b16cf <unknown>
#14 0x55ac073026b8 <unknown>
#15 0x55ac07302880 <unknown>
#16 0x55ac07312776 <unknown>
#17 0x7f752bd61ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/lhw.py", line 128, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x555eee3cc8fa <unknown>
#1 0x555eededdd20 <unknown>
#2 0x555eedf15438 <unknown>
#3 0x555eedf10f96 <unknown>
#4 0x555eedf5cd86 <unknown>
#5 0x555eedf5c3d6 <unknown>
#6 0x555eedf50893 <unknown>
#7 0x555eedf1f30d <unknown>
#8 0x555eedf2032e <unknown>
#9 0x555eee39900b <unknown>
#10 0x555eee39cf97 <unknown>
#11 0x555eee38571c <unknown>
#12 0x555eee39db17 <unknown>
#13 0x555eee36a6cf <unknown>
#14 0x555eee3bb6b8 <unknown>
#15 0x555eee3bb880 <unknown>
#16 0x555eee3cb776 <unknown>
#17 0x7f7f25ed0ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/lhw.py", line 128, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55c72073d8fa <unknown>
#1 0x55c72024ed20 <unknown>
#2 0x55c720286438 <unknown>
#3 0x55c720281f96 <unknown>
#4 0x55c7202cdd86 <unknown>
#5 0x55c7202cd3d6 <unknown>
#6 0x55c7202c1893 <unknown>
#7 0x55c72029030d <unknown>
#8 0x55c72029132e <unknown>
#9 0x55c72070a00b <unknown>
#10 0x55c72070df97 <unknown>
#11 0x55c7206f671c <unknown>
#12 0x55c72070eb17 <unknown>
#13 0x55c7206db6cf <unknown>
#14 0x55c72072c6b8 <unknown>
#15 0x55c72072c880 <unknown>
#16 0x55c72073c776 <unknown>
#17 0x7f17c06fbac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/lhw.py", line 128, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55d5688088fa <unknown>
#1 0x55d568319d20 <unknown>
#2 0x55d568351438 <unknown>
#3 0x55d56834cf96 <unknown>
#4 0x55d568398d86 <unknown>
#5 0x55d5683983d6 <unknown>
#6 0x55d56838c893 <unknown>
#7 0x55d56835b30d <unknown>
#8 0x55d56835c32e <unknown>
#9 0x55d5687d500b <unknown>
#10 0x55d5687d8f97 <unknown>
#11 0x55d5687c171c <unknown>
#12 0x55d5687d9b17 <unknown>
#13 0x55d5687a66cf <unknown>
#14 0x55d5687f76b8 <unknown>
#15 0x55d5687f7880 <unknown>
#16 0x55d568807776 <unknown>
#17 0x7f9175265ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/lhw.py", line 128, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5616ccbe88fa <unknown>
#1 0x5616cc6f9d20 <unknown>
#2 0x5616cc731438 <unknown>
#3 0x5616cc72cf96 <unknown>
#4 0x5616cc778d86 <unknown>
#5 0x5616cc7783d6 <unknown>
#6 0x5616cc76c893 <unknown>
#7 0x5616cc73b30d <unknown>
#8 0x5616cc73c32e <unknown>
#9 0x5616ccbb500b <unknown>
#10 0x5616ccbb8f97 <unknown>
#11 0x5616ccba171c <unknown>
#12 0x5616ccbb9b17 <unknown>
#13 0x5616ccb866cf <unknown>
#14 0x5616ccbd76b8 <unknown>
#15 0x5616ccbd7880 <unknown>
#16 0x5616ccbe7776 <unknown>
#17 0x7f6fcc296ac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/lhw.py", line 128, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559ceef798fa <unknown>
#1 0x559ceea8ad20 <unknown>
#2 0x559ceeac2438 <unknown>
#3 0x559ceeabdf96 <unknown>
#4 0x559ceeb09d86 <unknown>
#5 0x559ceeb093d6 <unknown>
#6 0x559ceeafd893 <unknown>
#7 0x559ceeacc30d <unknown>
#8 0x559ceeacd32e <unknown>
#9 0x559ceef4600b <unknown>
#10 0x559ceef49f97 <unknown>
#11 0x559ceef3271c <unknown>
#12 0x559ceef4ab17 <unknown>
#13 0x559ceef176cf <unknown>
#14 0x559ceef686b8 <unknown>
#15 0x559ceef68880 <unknown>
#16 0x559ceef78776 <unknown>
#17 0x7f0b7f7efac3 <unknown>

Traceback (most recent call last):
  File "/root/news_site_scraper/lhw.py", line 128, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56357f9418fa <unknown>
#1 0x56357f452d20 <unknown>
#2 0x56357f48a438 <unknown>
#3 0x56357f485f96 <unknown>
#4 0x56357f4d1d86 <unknown>
#5 0x56357f4d13d6 <unknown>
#6 0x56357f4c5893 <unknown>
#7 0x56357f49430d <unknown>
#8 0x56357f49532e <unknown>
#9 0x56357f90e00b <unknown>
#10 0x56357f911f97 <unknown>
#11 0x56357f8fa71c <unknown>
#12 0x56357f912b17 <unknown>
#13 0x56357f8df6cf <unknown>
#14 0x56357f9306b8 <unknown>
#15 0x56357f930880 <unknown>
#16 0x56357f940776 <unknown>
#17 0x7fe4a34faac3 <unknown>

